// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/28/2026, 12:13:56 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/Coding/DBMS_Proj/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Coding/DBMS_Proj/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Coding/DBMS_Proj/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Coding/DBMS_Proj/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Coding/DBMS_Proj/frontend/plugins/**/*.{js,ts,mjs}","E:/Coding/DBMS_Proj/frontend/composables/**/*.{js,ts,mjs}","E:/Coding/DBMS_Proj/frontend/utils/**/*.{js,ts,mjs}","E:/Coding/DBMS_Proj/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Coding/DBMS_Proj/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/Coding/DBMS_Proj/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/Coding/DBMS_Proj/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;