// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admins/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admins/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admins/[id].put').default>>>>
    }
    '/api/admins': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admins/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admins/index.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/customers/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/customers/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/customers/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/customers/[id].put').default>>>>
    }
    '/api/customers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/customers/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/customers/index.post').default>>>>
    }
    '/api/dashboard': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard.get').default>>>>
    }
    '/api/items/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/items/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/items/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/items/[id].put').default>>>>
    }
    '/api/items': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/items/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/items/index.post').default>>>>
    }
    '/api/purchases/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchases/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchases/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchases/[id].put').default>>>>
    }
    '/api/purchases': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchases/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchases/index.post').default>>>>
    }
    '/api/sales/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sales/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sales/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sales/[id].put').default>>>>
    }
    '/api/sales': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sales/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sales/index.post').default>>>>
    }
    '/api/vendors/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vendors/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vendors/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vendors/[id].put').default>>>>
    }
    '/api/vendors': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vendors/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vendors/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}